audit_header: false
title: San Juan del Sur and Tola
description: Our mission at Trinity Real Estate is to be your best resource for San Juan del Sur real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Trinity Real Estate, your professional San Juan del Sur Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /testimonials/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Joao Mucciolo
  title: Broker & Rainmaker
  license_number:
  about_markdown: |
    Joao has been an entrepreneur since 2003 in Nicaragua, bringing the Sushi Itto franchise to the country and creating his own brand:  Italianissimo. He created a company of 6 restaurants and more than 120 direct jobs.

    Brazilian by birth, and traveler of the world, Joao landed in Nicaragua more than 20 years ago and  considers himself today as Nica! He speaks Spanish, English, Portuguese, and a little French.

    Joao has contributed to entrepreneurship in Nicaragua, bringing organizations such as the Entrepreneurs Organization and Accelerator with the purpose of helping entrepreneurship grow. He is also a member of the Central American Leadership Initiative of the Aspen Institute where he strengthens his leadership skills.
  brand: Trinity Real Estate
  brokerage: Keller Williams
  market: San Juan del Sur
  address:
  phone: 505 88838829
  phone_type:
  phone2:
  phone2_type:
  email: Joao@trinityrealestatenicaragua.com
  # url: https://www.kwnicaragua.com/joao

CTAs:
  first_CTA_text: Listings Search
  first_CTA_URL: https://www.kwnicaragua.com/listings#?agentId=14319&agentName=Joao%20Mucciolo&resCom=0&transactionType=0&lan=es-NI&currency=USD&filterVal=1026&refineSearch=1&pageNumber=1
  second_CTA_text: Property Evaluation
  second_CTA_URL: /property-value/
  third_CTA_text: Rental Properties
  third_CTA_URL: https://selvapacifica.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/002.jpg
    CTA_title: "Looking for a San Juan del Sur or Tola Home?"
    CTA_text: "Search all residential properties available for sale"
    CTA_link_text: "Listings Search"
    CTA_url: https://www.kwnicaragua.com/listings#?agentId=14319&agentName=Joao%20Mucciolo&resCom=0&transactionType=0&lan=es-NI&currency=USD&filterVal=1026&refineSearch=1&pageNumber=1

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/001.jpg
    CTA_title2: "What’s Your Property Worth?"
    CTA_text2: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text2: "Property Evaluation"
    CTA_url2: /property-value/

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Vacation Homes That Are Extraordinary"
    CTA_text3: "With a curated a collection of exclusive, hand picked, luxury spaces—in all shapes and sizes—we provide the ultimate experiences in all of Nicaragua."
    CTA_link_text3: "Search Rental Properties"
    CTA_url3: https://selvapacifica.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/trinityrealestatenic/
  linkedin_url: https://www.linkedin.com/in/joao-mucciolo-7b2534/
  youtube_url: https://www.youtube.com/channel/UC7RxnXBs__0hN02eOs5xd8A?view_as=subscriber
  twitter_url:
  instagram_url: https://www.instagram.com/joaomucciolo/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://podcasts.apple.com/us/podcast/san-juan-del-sur-real-estate-podcast-with-joao-mucciolo/id1486357298

podcast:
  title: 'San Juan del Sur Real Estate Podcast with Joao Mucciolo'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Juan del Sur Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Trinity Real Estate - your professional San Juan del Sur Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Juan del Sur, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Joao Mucciolo'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: Blog de video inmobiliario de San Juan del Sur y Tola
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
